export { default as PrincipioComunicacion } from './PrincipioComunicacion'
export { default as PrincipioEmpatia } from './PrincipioEmpatia'
export { default as PrincipioJusticia } from './PrincipioJusticia'
export { default as PrincipioCritica } from './PrincipioCritica'
export { default as PrincipioPerdon } from './PrincipioPerdon'
export { default as PrincipioFe } from './PrincipioFe'

export { default as Integridad } from './Integridad'
export { default as Perseverancia } from './Perseverancia'
export { default as Humildad } from './Humildad'
export { default as Responsabilidad } from './Responsabilidad'
export { default as Respeto } from './Respeto'
export { default as Colaboracion } from './Colaboracion'
export { default as Gratitud } from './Gratitud'
export { default as VotosExitoBook } from './VotosExitoBook'
export { default as VotosAplicacion } from './VotosAplicacion'
